from typing import Final

from options import FrameType

DEBUG: Final = True

FFMPEG_COMMAND: Final = 'ffmpeg -y -f concat -safe 0 -i {path_listfile} -i {path_audio} -c:v libx264 -c:a copy -vf "fps={framerate},format=yuv420p" -shortest {path_output} -hide_banner'

FRAMERATE: Final = 25
PATH_LISTFILE: Final = "out_listfile.txt"
PATH_AUDIO_ORIGINAL: Final = "audio.aac"
PATH_OUTPUT: Final = "out.mp4"

# TODO: Fix timings
TIMINGS: Final = [
	{'type': FrameType.IDLE, 'dur': 50},
    {'type': FrameType.GETDOWN, 'dur': 12},
    {'type': FrameType.GETDOWN, 'dur': 12},
    *[{'type': FrameType.RANDOM, 'dur': 1}] * 216,
    {'type': FrameType.HIPSHAKE, 'dur': 1},
    {'type': FrameType.HIPSHAKE, 'dur': 4},
    {'type': FrameType.HIPSHAKE, 'dur': 2},
    {'type': FrameType.HIPSHAKE, 'dur': 1},
    {'type': FrameType.HIPSHAKE, 'dur': 4},
    {'type': FrameType.HIPSHAKE, 'dur': 2},
    {'type': FrameType.HIPSHAKE, 'dur': 2},
    {'type': FrameType.HIPSHAKE, 'dur': 1},
    {'type': FrameType.HIPSHAKE, 'dur': 2},
    {'type': FrameType.HIPSHAKE, 'dur': 1},
    *[{'type': FrameType.RANDOM, 'dur': 1}] * 26,
    {'type': FrameType.HIPSHAKE, 'dur': 1},
    {'type': FrameType.HIPSHAKE, 'dur': 4},
    {'type': FrameType.HIPSHAKE, 'dur': 2},
    {'type': FrameType.HIPSHAKE, 'dur': 2},
    {'type': FrameType.HIPSHAKE, 'dur': 1},
    {'type': FrameType.HIPSHAKE, 'dur': 1},
    {'type': FrameType.HIPSHAKE, 'dur': 4},
    {'type': FrameType.HIPSHAKE, 'dur': 2},
    {'type': FrameType.HIPSHAKE, 'dur': 2},
    {'type': FrameType.HIPSHAKE, 'dur': 1},
    {'type': FrameType.HIPTHRUST, 'dur': 4},
    {'type': FrameType.HIPTHRUST, 'dur': 3},
    {'type': FrameType.HIPTHRUST, 'dur': 3},
    {'type': FrameType.HIPTHRUST, 'dur': 3},
    {'type': FrameType.HIPTHRUST, 'dur': 3},
    {'type': FrameType.HIPTHRUST, 'dur': 3},
    {'type': FrameType.HIPTHRUST, 'dur': 4},
    {'type': FrameType.HIPTHRUST, 'dur': 2},
    {'type': FrameType.HIPTHRUST, 'dur': 4},
    {'type': FrameType.HIPTHRUST, 'dur': 3},
    {'type': FrameType.HIPTHRUST, 'dur': 3},
    {'type': FrameType.HIPTHRUST, 'dur': 3},
    {'type': FrameType.HIPTHRUST, 'dur': 3},
    {'type': FrameType.HIPTHRUST, 'dur': 3},
    {'type': FrameType.HIPTHRUST, 'dur': 4},
    {'type': FrameType.HIPTHRUST, 'dur': 2},
    {'type': FrameType.HIPTHRUST, 'dur': 4},
    {'type': FrameType.HIPTHRUST, 'dur': 3},
    {'type': FrameType.HIPTHRUST, 'dur': 11},
    {'type': FrameType.CHIKAU, 'dur': 11},
    {'type': FrameType.CHIKAU, 'dur': 12},
	{'type': FrameType.CHIKAU, 'dur': 12},
    *[{'type': FrameType.RANDOM, 'dur': 1}] * 216,
    {'type': FrameType.HIPSHAKE, 'dur': 1},
    {'type': FrameType.HIPSHAKE, 'dur': 4},
    {'type': FrameType.HIPSHAKE, 'dur': 2},
    {'type': FrameType.HIPSHAKE, 'dur': 2},
    {'type': FrameType.HIPSHAKE, 'dur': 1},
	{'type': FrameType.HIPSHAKE, 'dur': 1},
    {'type': FrameType.HIPSHAKE, 'dur': 4},
    {'type': FrameType.HIPSHAKE, 'dur': 2},
    {'type': FrameType.HIPSHAKE, 'dur': 2},
    {'type': FrameType.HIPSHAKE, 'dur': 1},
    *[{'type': FrameType.RANDOM, 'dur': 1}] * 26,
    {'type': FrameType.HIPSHAKE, 'dur': 1},
    {'type': FrameType.HIPSHAKE, 'dur': 4},
    {'type': FrameType.HIPSHAKE, 'dur': 2},
    {'type': FrameType.HIPSHAKE, 'dur': 2},
    {'type': FrameType.HIPSHAKE, 'dur': 1},
	{'type': FrameType.HIPSHAKE, 'dur': 1},
    {'type': FrameType.HIPSHAKE, 'dur': 4},
    {'type': FrameType.HIPSHAKE, 'dur': 2},
    {'type': FrameType.HIPSHAKE, 'dur': 2},
    {'type': FrameType.HIPSHAKE, 'dur': 1},
    {'type': FrameType.HIPTHRUST, 'dur': 4},
    {'type': FrameType.HIPTHRUST, 'dur': 3},
    {'type': FrameType.HIPTHRUST, 'dur': 3},
    {'type': FrameType.HIPTHRUST, 'dur': 3},
    {'type': FrameType.HIPTHRUST, 'dur': 3},
    {'type': FrameType.HIPTHRUST, 'dur': 3},
    {'type': FrameType.HIPTHRUST, 'dur': 4},
    {'type': FrameType.HIPTHRUST, 'dur': 2},
    {'type': FrameType.HIPTHRUST, 'dur': 4},
    {'type': FrameType.HIPTHRUST, 'dur': 3},
    {'type': FrameType.HIPTHRUST, 'dur': 3},
    {'type': FrameType.HIPTHRUST, 'dur': 3},
    {'type': FrameType.HIPTHRUST, 'dur': 3},
    {'type': FrameType.HIPTHRUST, 'dur': 3},
    {'type': FrameType.HIPTHRUST, 'dur': 4},
    {'type': FrameType.HIPTHRUST, 'dur': 2},
    {'type': FrameType.HIPTHRUST, 'dur': 4},
    {'type': FrameType.HIPTHRUST, 'dur': 3},
    {'type': FrameType.HIPTHRUST, 'dur': 11},
    {'type': FrameType.CHIKAU, 'dur': 11},
    {'type': FrameType.CHIKAU, 'dur': 12},
	{'type': FrameType.CHIKAU, 'dur': 12},
    *[{'type': FrameType.RANDOM, 'dur': 1}] * 101,
    {'type': FrameType.IDLE, 'dur': 93},
    {'type': FrameType.IDLE, 'dur': 0},
]
